In [2]:
"""
Load required libraries
"""
# External libraries
import pandas as pd
import numpy as np
import sys
import ast

# Internal libraries
import input
import model
import training
import output
import utils

2024-12-09 12:25:37.412379: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-09 12:25:37.489294: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-09 12:25:37.506415: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-09 12:25:37.512232: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-09 12:25:37.568584: I tensorflow/core/platform/cpu_feature_guar

In [3]:
input.BSk24_VARIANS[input.BSk24_VARIANS['varian_id']==1]

varian_id  param(01)  param(02)  param(03)  param(04)  param(05)  \
0          1  -3970.301   395.8715    0.00001   22648.46  -100.1343   

   param(06)  param(07)  param(08)    param(09)  ...  sigma_L       M*s  \
0  -149.9985   0.894522   0.064016 -138961900.0  ...      0.0  0.799926   

      <M*s>  sigma_M*s       M*v     <M*v>  sigma_M*v       rms     <rms>  \
0  0.799926        0.0  0.715061  0.715061        0.0  1.733691  1.733691   

   sigma_rms  
0        0.0  

[1 rows x 46 columns]

In [4]:
input.BSk24_MASS_TABLE

Z    N    A       m
0       8    8   16   -2.75
1       8    9   17    1.27
2       8   10   18    0.93
3       8   11   19    5.15
4       8   12   20    3.24
...   ...  ...  ...     ...
8387  110  246  356  532.90
8388  110  247  357  540.13
8389  110  248  358  548.25
8390  110  249  359  555.30
8391  110  250  360  563.45

[8392 rows x 4 columns]

In [5]:
u = pd.merge(input.BSk24_VARIANS_MASS_TABLE, input.BSk24_VARIANS, on='varian_id')
u

varian_id    Z    N    A           m  param(01)  param(02)  param(03)  \
0             1    8   13   21    6.653146  -3970.301   395.8715    0.00001   
1             1    8   16   24   15.525280  -3970.301   395.8715    0.00001   
2             1    9   14   23   -0.606974  -3970.301   395.8715    0.00001   
3             1    9   17   26   14.968190  -3970.301   395.8715    0.00001   
4             1   10   14   24   -8.670079  -3970.301   395.8715    0.00001   
...         ...  ...  ...  ...         ...        ...        ...        ...   
7285         10  103  153  256   89.304250  -3970.313   395.8304    0.00001   
7286         10  104  154  258   95.046090  -3970.313   395.8304    0.00001   
7287         10  106  154  260  105.307500  -3970.313   395.8304    0.00001   
7288         10  108  156  264  118.535500  -3970.313   395.8304    0.00001   
7289         10  110  159  269  131.752300  -3970.313   395.8304    0.00001   

      param(04)  param(05)  ...  sigma_L       M*s     <M*s>  sigma_M*s  \
0      22648.46  -100.1343  ...  0.00000  0.799926  0.799926   0.000000   
1      22648.46  -100.1343  ...  0.00000  0.799926  0.799926   0.000000   
2      22648.46  -100.1343  ...  0.00000  0.799926  0.799926   0.000000   
3      22648.46  -100.1343  ...  0.00000  0.799926  0.799926   0.000000   
4      22648.46  -100.1343  ...  0.00000  0.799926  0.799926   0.000000   
...         ...        ...  ...      ...       ...       ...        ...   
7285   22648.83  -100.2015  ...  0.78071  0.800058  0.799994   0.000062   
7286   22648.83  -100.2015  ...  0.78071  0.800058  0.799994   0.000062   
7287   22648.83  -100.2015  ...  0.78071  0.800058  0.799994   0.000062   
7288   22648.83  -100.2015  ...  0.78071  0.800058  0.799994   0.000062   
7289   22648.83  -100.2015  ...  0.78071  0.800058  0.799994   0.000062   

           M*v     <M*v>  sigma_M*v       rms     <rms>  sigma_rms  
0     0.715061  0.715061   0.000000  1.733691  1.733691   0.000000  
1     0.715061  0.715061   0.000000  1.733691  1.733691   0.000000  
2     0.715061  0.715061   0.000000  1.733691  1.733691   0.000000  
3     0.715061  0.715061   0.000000  1.733691  1.733691   0.000000  
4     0.715061  0.715061   0.000000  1.733691  1.733691   0.000000  
...        ...       ...        ...       ...       ...        ...  
7285  0.717442  0.713625   0.001992  1.398419  1.488712   0.524705  
7286  0.717442  0.713625   0.001992  1.398419  1.488712   0.524705  
7287  0.717442  0.713625   0.001992  1.398419  1.488712   0.524705  
7288  0.717442  0.713625   0.001992  1.398419  1.488712   0.524705  
7289  0.717442  0.713625   0.001992  1.398419  1.488712   0.524705  

[7290 rows x 50 columns]

In [10]:
u.iloc[:,5:26].to_numpy()

array([[-3.970301e+03,  3.958715e+02,  1.000058e-05, ...,  1.076115e+00,
         1.084184e+00,  1.615400e+01],
       [-3.970301e+03,  3.958715e+02,  1.000058e-05, ...,  1.076115e+00,
         1.084184e+00,  1.615400e+01],
       [-3.970301e+03,  3.958715e+02,  1.000058e-05, ...,  1.076115e+00,
         1.084184e+00,  1.615400e+01],
       ...,
       [-3.970313e+03,  3.958304e+02,  1.000049e-05, ...,  1.092640e+00,
         1.043076e+00,  1.633400e+01],
       [-3.970313e+03,  3.958304e+02,  1.000049e-05, ...,  1.092640e+00,
         1.043076e+00,  1.633400e+01],
       [-3.970313e+03,  3.958304e+02,  1.000049e-05, ...,  1.092640e+00,
         1.043076e+00,  1.633400e+01]])

In [11]:
input.BSk24.to_numpy()

array([[-3.97029000e+03,  3.95766000e+02,  0.00000000e+00,
         2.26486000e+04, -1.00000000e+02, -1.50000000e+02,
         8.94371000e-01,  5.63535000e-02,             nan,
         1.05119000e+00,  2.00000000e+00, -1.10000000e+01,
         8.33333333e-02,  5.00000000e-01,  8.33333333e-02,
         1.08405000e+02,  1.00000000e+00,  1.06000000e+00,
         1.09000000e+00,  1.16000000e+00,  1.60000000e+01]])

In [17]:
bsk24_param = input.data.BSk24
bsk24_mass_table = input.data.BSk24_MASS_TABLE
bsk24_varians_param = input.data.BSk24_VARIANS
bsk24_varians_mass_table = input.data.BSk24_VARIANS_MASS_TABLE

# Sampling the varian
varian_number = 5 # Pick any number between 1 and 10
varian_param = bsk24_varians_param[bsk24_varians_param['varian_id']==varian_number]
varian_mass_table = bsk24_varians_mass_table[bsk24_varians_mass_table['varian_id']==varian_number]
selected_varian = pd.merge(varian_mass_table, varian_param, on='varian_id')
selected_varian = selected_varian.sample(frac=0.1).reset_index(drop=True)

Z_bsk24 = bsk24_mass_table['Z']
N_bsk24 = bsk24_mass_table['N']
m_bsk24 = bsk24_mass_table['m']
param_bsk24 = input.data.BSk24.to_numpy() 

Z_bsk24_varian = selected_varian['Z']
N_bsk24_varian = selected_varian['N']
m_bsk24_varian = selected_varian['m']
params_bsk24_varian = selected_varian.iloc[:,5:26].to_numpy()

# Generate the input date
Z = np.concatenate((Z_bsk24, Z_bsk24_varian))
N = np.concatenate((N_bsk24, N_bsk24_varian))
m = np.concatenate((m_bsk24, m_bsk24_varian))
params = np.concatenate((param_bsk24, params_bsk24_varian))

In [18]:
params

array([[-3.970290e+03,  3.957660e+02,  0.000000e+00, ...,  1.090000e+00,
         1.160000e+00,  1.600000e+01],
       [-3.970318e+03,  3.959483e+02,  1.000050e-05, ...,  1.053995e+00,
         1.078238e+00,  1.634200e+01],
       [-3.970318e+03,  3.959483e+02,  1.000050e-05, ...,  1.053995e+00,
         1.078238e+00,  1.634200e+01],
       ...,
       [-3.970318e+03,  3.959483e+02,  1.000050e-05, ...,  1.053995e+00,
         1.078238e+00,  1.634200e+01],
       [-3.970318e+03,  3.959483e+02,  1.000050e-05, ...,  1.053995e+00,
         1.078238e+00,  1.634200e+01],
       [-3.970318e+03,  3.959483e+02,  1.000050e-05, ...,  1.053995e+00,
         1.078238e+00,  1.634200e+01]])

In [19]:
params.shape

(74, 21)

In [29]:
len(Z_bsk24)

8392

In [ ]:
param_bsk24 = np.tile(param_bsk24, (len(Z_bsk24), 1))

In [37]:
param_bsk24.shape


(8392, 21)

In [28]:
import numpy as np

# Example array with one row
arr = np.array([1, 2, 3, 4])  # Shape (1, 4)

# Repeat the array to create 20 identical rows
arr_repeated = np.tile(arr, (20, 1))  # Repeat the row 20 times along the row axis

print(arr_repeated)
print(arr_repeated.shape)  # Should output (20, 4)


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
(20, 4)


In [35]:
params = np.concatenate((param_bsk24, params_bsk24_varian))

In [36]:
params.shape

(8465, 21)

In [38]:
import numpy as np

# Example data
wouter_dat = np.random.randn(8465, 11)  # Shape (8465, 11)
param = np.random.randn(8465, 21)       # Shape (8465, 21)

# Ensure param is of shape (8465, 21)
assert wouter_dat.shape[0] == param.shape[0], "Rows do not match!"

# Insert param starting from column 10 (11th column) along axis 1
complete_dat = np.insert(wouter_dat, 10, param, axis=1)

print(complete_dat.shape)  # Should output (8465, 32)


ValueError: could not broadcast input array from shape (21,8465) into shape (8465,8465)

In [39]:
wouter_dat.shape

(8465, 11)

In [40]:
param.shape

(8465, 21)

In [44]:
"""
Importing required libraries
"""
#External Library
import numpy as np
import pandas as pd
from keras import models, layers, callbacks
import os
import tensorflow as tf
import sys
import ast

#Internal Library
from input import *
from model import *
from training import *
from output import *
from utils import *

model = wouter_model(31, 'adadelta')
model.load_weights('training/weight_best/sample_test=[150,25,25].batch=4.epoch=100.stage3.weights.h5')
selected_varian = pd.merge(varian_mass_table, varian_param, on='varian_id')

generate_mass_table(model, selected_varian, training_label)

/opt/miniconda3/envs/tf/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adadelta', because it has 2 variables whereas the saved optimizer has 10 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


NameError: name 'generate_mass_table' is not defined